# Generated by Django 3.1.2 on 2020-10-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_signing', models.DateField(verbose_name='Дата подписания')),
                ('side', models.CharField(choices=[('Поставщик', 'Поставщик'), ('Покупатель', 'Покупатель')], default='Покупатель', max_length=10, verbose_name='Сторона в договоре')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование Организации')),
                ('director', models.CharField(max_length=100, verbose_name='Генеральный директор')),
                ('legal_address', models.CharField(max_length=254, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('number_of_contract', models.CharField(max_length=250, verbose_name='Номер договора')),
                ('terms', models.TextField(null=True, verbose_name='Содержание работ')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('file', models.FileField(blank=True, upload_to='static/uploads/%Y/%m/%d/', verbose_name='Прикрепленный файл')),
                ('period_of_execution', models.DateField(verbose_name='Срок выполнения')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('На этапе оплаты', 'На этапе оплаты'), ('На этапе подписывания', 'На этапе подписывания')], default='На этапе подписывания', max_length=21, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Задача')),
                ('date', models.DateField(verbose_name='Срок выполнения')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Точка контроля',
                'verbose_name_plural': 'Точки контроля',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_period', models.DateField(verbose_name='Срок исполнения')),
                ('subject', models.CharField(max_length=200, verbose_name='Количество товара')),
                ('payment_period', models.DateField(verbose_name='Срок оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма')),
                ('penalty', models.FloatField(verbose_name='Неустойка')),
                ('reaction', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], default='Не выполнено', max_length=12, verbose_name='Реакция')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contract')),
            ],
            options={
                'verbose_name': 'Срок',
                'verbose_name_plural': 'Сроки',
            },
        ),
    ]
