# Generated by Django 3.1.2 on 2020-10-26 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201027_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='now',
            field=models.DateField(default=datetime.date.today, verbose_name='Сегодня'),
        ),
    ]
