# Generated by Django 3.1.2 on 2020-10-26 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201027_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='now_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
