# Generated by Django 3.1.2 on 2020-10-26 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_timing_now_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
