# Generated by Django 3.1.2 on 2020-10-27 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201027_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='now_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
