# Generated by Django 3.1.2 on 2020-10-27 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201027_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='now_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
