# Generated by Django 3.1.2 on 2020-10-27 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201027_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='now_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 3, 16, 47, 518150)),
        ),
    ]
