# Generated by Django 3.1.2 on 2020-10-27 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201027_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='now',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='now_time',
        ),
        migrations.AlterField(
            model_name='now',
            name='now_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 3, 18, 29, 436619)),
        ),
    ]
