# Generated by Django 3.1.2 on 2020-10-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201027_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='now',
            name='now',
        ),
    ]
