# Generated by Django 3.1.2 on 2020-10-27 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_now_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='now',
            name='now',
            field=models.DateField(default=datetime.date(2020, 10, 27)),
        ),
    ]
