# Generated by Django 3.1.2 on 2020-10-27 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_now_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='now',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 3, 46, 21, 230190)),
        ),
    ]
