# Generated by Django 3.1.2 on 2020-10-27 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201027_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='now',
            name='now',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 10, 11, 158099)),
        ),
        migrations.AlterField(
            model_name='timing',
            name='subject',
            field=models.IntegerField(verbose_name='Количество обещанного товара'),
        ),
    ]
