# Generated by Django 3.1.2 on 2020-10-27 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201027_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='delivered',
            field=models.IntegerField(default=0, verbose_name='Количество обещанного товара'),
        ),
        migrations.AddField(
            model_name='timing',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Заплачено'),
        ),
        migrations.AlterField(
            model_name='now',
            name='now',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 24, 36, 109670)),
        ),
    ]
