# Generated by Django 3.1.2 on 2020-10-27 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201027_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='now',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 17, 41, 43, 497166)),
        ),
    ]
